steps:
  # 1. Build the Container Image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/rukmer-saas',
      '--build-arg', 'VITE_GEMINI_API_KEY=$_VITE_GEMINI_API_KEY',
      '--build-arg', 'VITE_FIREBASE_API_KEY=$_VITE_FIREBASE_API_KEY',
      '--build-arg', 'VITE_FIREBASE_AUTH_DOMAIN=$_VITE_FIREBASE_AUTH_DOMAIN',
      '--build-arg', 'VITE_FIREBASE_PROJECT_ID=$_VITE_FIREBASE_PROJECT_ID',
      '--build-arg', 'VITE_FIREBASE_STORAGE_BUCKET=$_VITE_FIREBASE_STORAGE_BUCKET',
      '--build-arg', 'VITE_FIREBASE_MESSAGING_SENDER_ID=$_VITE_FIREBASE_MESSAGING_SENDER_ID',
      '--build-arg', 'VITE_FIREBASE_APP_ID=$_VITE_FIREBASE_APP_ID',
      '--build-arg', 'VITE_FIREBASE_MEASUREMENT_ID=$_VITE_FIREBASE_MEASUREMENT_ID',
      '--build-arg', 'VITE_API_URL=$_VITE_API_URL',
      '.'
    ]

  # 2. Push the Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rukmer-saas']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy',
      'rukmer-saas-service',
      '--image', 'gcr.io/$PROJECT_ID/rukmer-saas',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--add-cloudsql-instances', 'rukmer-saas:us-central1:rukmer-saas-ai',
      '--update-env-vars',
      'NODE_ENV=${_NODE_ENV},DB_USER=${_DB_USER},DB_NAME=${_DB_NAME},DB_PASSWORD=${_DB_PASSWORD},INSTANCE_CONNECTION_NAME=rukmer-saas:us-central1:rukmer-saas-ai'
    ]

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
    _VITE_GEMINI_API_KEY: ''
    _VITE_FIREBASE_API_KEY: ''
    _VITE_FIREBASE_AUTH_DOMAIN: ''
    _VITE_FIREBASE_PROJECT_ID: ''
    _VITE_FIREBASE_STORAGE_BUCKET: ''
    _VITE_FIREBASE_MESSAGING_SENDER_ID: ''
    _VITE_FIREBASE_APP_ID: ''
    _VITE_FIREBASE_MEASUREMENT_ID: ''
    _NODE_ENV: ''
    _DB_USER: ''
    _DB_NAME: ''
    _DB_PASSWORD: ''
    _INSTANCE_CONNECTION_NAME: ''
    _VITE_API_URL: ''